/**
 * FORTUNA ENGINE v6 — CPA Export Package Generator
 * 
 * Generates comprehensive, professional handoff documents
 * that CPAs and tax preparers can use directly. Includes:
 * - Income summary with source categorization
 * - Deduction inventory with documentation status
 * - Entity structure overview
 * - Strategy recommendations requiring professional implementation
 * - Estimated tax position summary
 * - Audit risk factors to review
 */

import type { FortunaState } from './storage'
import { generateTaxReport } from './tax-calculator'
import { analyzeAuditRisk } from './audit-risk'
import { detectStrategies } from './strategy-detector'
import { generateHealthReport } from './health-score'
import { hasPortfolioData, computePortfolioSummary, generateForm8949Data, getPortfolioData } from './portfolio-bridge'

export interface CPAExportSection {
  title: string
  content: string
}

export interface CPAExportPackage {
  generatedDate: string
  taxYear: number
  clientName: string
  filingStatus: string
  state: string
  sections: CPAExportSection[]
  rawText: string
}

function formatCurrency(n: number): string {
  return '$' + Math.round(n).toLocaleString()
}

export function generateCPAExport(state: FortunaState): CPAExportPackage {
  const { profile, incomeStreams, expenses, deductions, entities } = state
  const taxReport = generateTaxReport(state)
  const auditRisk = analyzeAuditRisk(state)
  const strategies = detectStrategies(state)
  const health = generateHealthReport(state)
  const year = new Date().getFullYear()

  const sections: CPAExportSection[] = []

  // ─── Section 1: Client Overview ────────────────────────────────────

  sections.push({
    title: 'CLIENT OVERVIEW',
    content: [
      `Name:           ${profile.name || 'Not provided'}`,
      `Filing Status:  ${profile.filingStatus || 'Single'}`,
      `State:          ${profile.state || 'Not specified'}`,
      `Age:            ${profile.age || 'Not provided'}`,
      `Dependents:     ${profile.dependents ?? 0}`,
      `Tax Year:       ${year}`,
      ``,
      `Financial Health Score: ${health.overallScore}/100 (${health.overallGrade})`,
      `Report Generated:      ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`,
      `Generated By:          Fortuna Engine v6`,
    ].join('\n'),
  })

  // ─── Section 2: Income Summary ─────────────────────────────────────

  const activeStreams = incomeStreams.filter(s => s.isActive)
  const totalIncome = activeStreams.reduce((sum, s) => sum + s.annualAmount, 0)
  const selfEmploymentIncome = activeStreams
    .filter(s => ['business', 'freelance'].includes(s.type))
    .reduce((sum, s) => sum + s.annualAmount, 0)
  const w2Income = activeStreams
    .filter(s => s.type === 'w2')
    .reduce((sum, s) => sum + s.annualAmount, 0)
  const investmentIncome = activeStreams
    .filter(s => s.type === 'investment')
    .reduce((sum, s) => sum + s.annualAmount, 0)
  const otherIncome = totalIncome - selfEmploymentIncome - w2Income - investmentIncome

  const incomeLines = activeStreams.map(s =>
    `  ${s.name.padEnd(35)} ${s.type.padEnd(15)} ${formatCurrency(s.annualAmount).padStart(12)}`
  )

  sections.push({
    title: 'INCOME SUMMARY',
    content: [
      `Source                              Type            Amount`,
      `${'─'.repeat(65)}`,
      ...incomeLines,
      `${'─'.repeat(65)}`,
      `  ${'TOTAL GROSS INCOME'.padEnd(50)} ${formatCurrency(totalIncome).padStart(12)}`,
      ``,
      `Breakdown:`,
      `  Self-Employment (Sched C/SE):  ${formatCurrency(selfEmploymentIncome)}`,
      `  W-2 Employment:                ${formatCurrency(w2Income)}`,
      `  Investment Income:             ${formatCurrency(investmentIncome)}`,
      `  Other:                         ${formatCurrency(otherIncome)}`,
    ].join('\n'),
  })

  // ─── Section 3: Business Expenses ──────────────────────────────────

  const deductibleExpenses = expenses.filter(e => e.isDeductible)
  const totalDeductible = deductibleExpenses.reduce((sum, e) => sum + (e.annualAmount * e.deductionPct / 100), 0)

  const expenseLines = deductibleExpenses.map(e =>
    `  ${e.name.padEnd(30)} ${(e.category || 'other').padEnd(15)} ${formatCurrency(e.annualAmount).padStart(10)}  ${(e.deductionPct + '%').padStart(5)}  ${formatCurrency(e.annualAmount * e.deductionPct / 100).padStart(10)}`
  )

  sections.push({
    title: 'BUSINESS EXPENSES & DEDUCTIONS',
    content: [
      `Expense                        Category         Gross       Ded%   Deductible`,
      `${'─'.repeat(80)}`,
      ...(expenseLines.length > 0 ? expenseLines : ['  No business expenses recorded']),
      `${'─'.repeat(80)}`,
      `  ${'TOTAL DEDUCTIBLE EXPENSES'.padEnd(57)} ${formatCurrency(totalDeductible).padStart(10)}`,
      ``,
      `Additional Deductions:`,
      ...deductions.map(d =>
        `  ${d.name.padEnd(40)} ${d.category.padEnd(15)} ${formatCurrency(d.amount).padStart(12)}`
      ),
      deductions.length === 0 ? '  No additional deductions recorded' : '',
      ``,
      `Net Self-Employment Income:  ${formatCurrency(selfEmploymentIncome - totalDeductible)}`,
    ].join('\n'),
  })

  // ─── Section 4: Entity Structure & P&L ──────────────────────────────

  const activeEntities = entities.filter(e => e.isActive)
  const entityTypeLabels: Record<string, string> = {
    'sole_prop': 'Sole Proprietorship',
    'llc': 'LLC (Disregarded)',
    'llc_scorp': 'LLC (S-Corp Election)',
    'scorp': 'S-Corporation',
    'ccorp': 'C-Corporation',
    'partnership': 'Partnership',
    'trust': 'Trust / Estate',
  }

  const entityPnLLines = (taxReport.entityBreakdown || [])
    .filter(e => e.revenue > 0 || e.expenses > 0)
    .map(e => [
      `  Entity:       ${e.entityName}`,
      `  Type:         ${entityTypeLabels[e.entityType] || e.entityType}`,
      `  Flow-Through: ${e.flowThrough === 'schedule_c' ? 'Schedule C' : e.flowThrough === 'k1' ? 'K-1 Pass-Through' : e.flowThrough === 'corporate' ? 'Corporate Return' : 'Personal Return'}`,
      `  Revenue:      ${formatCurrency(e.revenue)}`,
      `  Expenses:     ${formatCurrency(e.expenses)}`,
      `  Net Income:   ${formatCurrency(e.netIncome)}`,
      ...(e.officerSalary > 0 ? [
        `  Officer W-2:  ${formatCurrency(e.officerSalary)}`,
        `  Distributions:${formatCurrency(e.distributions)}`,
      ] : []),
      ...(e.seTaxableAmount > 0 ? [`  SE Taxable:   ${formatCurrency(e.seTaxableAmount)}`] : []),
      ...(e.qbiEligibleAmount > 0 ? [`  QBI Eligible: ${formatCurrency(e.qbiEligibleAmount)}`] : []),
      ``,
    ].join('\n'))

  sections.push({
    title: 'ENTITY STRUCTURE & FINANCIALS',
    content: [
      activeEntities.length > 0
        ? [
          ...activeEntities.map(e => [
            `  Entity:  ${e.name}`,
            `  Type:    ${entityTypeLabels[e.type] || e.type}`,
            `  EIN:     ${e.einNumber || 'Not provided'}`,
            `  State:   ${e.state || profile.state || 'N/A'}`,
            ...(e.ownershipPct && e.ownershipPct < 100 ? [`  Ownership: ${e.ownershipPct}%`] : []),
            ``,
          ].join('\n')),
        ].join('\n')
        : '  Operating as Sole Proprietor (no formal entity)',
      ``,
      `ENTITY-LEVEL P&L SUMMARY:`,
      entityPnLLines.length > 0
        ? entityPnLLines.join('\n')
        : '  No entity-level financial data available',
      ``,
      `ENTITY RECOMMENDATIONS:`,
      ...strategies
        .filter(s => s.category === 'entity')
        .map(s => `  • ${s.title}: ${s.description}`),
      strategies.filter(s => s.category === 'entity').length === 0
        ? '  No entity changes recommended at this time'
        : '',
    ].join('\n'),
  })

  // ─── Section 5: Tax Position Estimate ──────────────────────────────

  sections.push({
    title: 'ESTIMATED TAX POSITION',
    content: [
      `Adjusted Gross Income:           ${formatCurrency(taxReport.agi)}`,
      `Standard/Itemized Deduction:     ${formatCurrency(taxReport.standardDeduction || 0)}`,
      `Taxable Income:                  ${formatCurrency(taxReport.taxableIncome)}`,
      ``,
      `Federal Income Tax:              ${formatCurrency(taxReport.federalIncomeTax)}`,
      `Self-Employment Tax:             ${formatCurrency(taxReport.selfEmploymentTax)}`,
      `Total Federal Tax:               ${formatCurrency(taxReport.totalFederalTax)}`,
      ``,
      `Effective Federal Rate:          ${taxReport.effectiveRate.toFixed(1)}%`,
      `Marginal Rate:                   ${taxReport.marginalRate}%`,
      ``,
      `Quarterly Estimated Payment:     ${formatCurrency(taxReport.totalFederalTax / 4)}`,
      ``,
      `NOTE: These are estimates based on client-provided data.`,
      `Actual figures may differ based on complete return preparation.`,
    ].join('\n'),
  })

  // ─── Section 6: Strategy Recommendations ───────────────────────────

  const highPriorityStrategies = strategies.filter(s => s.priority === 'critical' || s.priority === 'high')
  const mediumStrategies = strategies.filter(s => s.priority === 'medium')

  sections.push({
    title: 'STRATEGY RECOMMENDATIONS FOR PROFESSIONAL REVIEW',
    content: [
      `HIGH PRIORITY:`,
      ...(highPriorityStrategies.length > 0
        ? highPriorityStrategies.map((s, i) => [
          `  ${i + 1}. ${s.title}`,
          `     ${s.description}`,
          `     Estimated Impact: ${formatCurrency(s.estimatedImpact)}/yr`,
          ``,
        ].join('\n'))
        : ['  No high-priority strategies identified']),
      ``,
      `MEDIUM PRIORITY:`,
      ...(mediumStrategies.length > 0
        ? mediumStrategies.map((s, i) => [
          `  ${i + 1}. ${s.title}`,
          `     ${s.description}`,
          s.estimatedImpact > 0 ? `     Estimated Impact: ${formatCurrency(s.estimatedImpact)}/yr` : '',
          ``,
        ].join('\n'))
        : ['  No medium-priority strategies identified']),
      ``,
      `Total Estimated Annual Savings Potential: ${formatCurrency(strategies.reduce((sum, s) => sum + s.estimatedImpact, 0))}`,
    ].join('\n'),
  })

  // ─── Section 7: Audit Risk Assessment ──────────────────────────────

  const highRiskFactors = auditRisk.triggers.filter(f => f.riskScore > 50)

  sections.push({
    title: 'AUDIT RISK ASSESSMENT',
    content: [
      `Overall Risk Score: ${auditRisk.overallScore}/100 (${auditRisk.overallScore < 30 ? 'LOW' : auditRisk.overallScore < 60 ? 'MODERATE' : 'ELEVATED'})`,
      ``,
      `ELEVATED RISK FACTORS:`,
      ...(highRiskFactors.length > 0
        ? highRiskFactors.map(f => `  ⚠ ${f.name}: ${f.riskScore}/100 — ${f.description}`)
        : ['  No elevated risk factors identified']),
      ``,
      `MITIGATION RECOMMENDATIONS:`,
      ...auditRisk.topRecommendations.slice(0, 5).map(r => `  • ${r}`),
      ``,
      `NOTE: Risk scores are estimates based on IRS DIF scoring patterns.`,
      `Actual audit selection involves additional factors.`,
    ].join('\n'),
  })

  // ─── Section 8: Key Deadlines ──────────────────────────────────────

  // ── Portfolio & Investment Income ────────────────────────────────
  if (hasPortfolioData()) {
    const ps = computePortfolioSummary()
    const f8949 = generateForm8949Data()
    const portfolio = getPortfolioData()
    const lines: string[] = []

    lines.push('PORTFOLIO OVERVIEW:')
    lines.push(`  Active Positions: ${ps.activePositionCount}`)
    lines.push(`  Total Portfolio Value: $${Math.round(ps.totalValue).toLocaleString()}`)
    lines.push(`  Total Cost Basis: $${Math.round(ps.totalCostBasis).toLocaleString()}`)
    lines.push(`  Unrealized Gain/Loss: ${ps.unrealizedGainLoss >= 0 ? '+' : ''}$${Math.round(ps.unrealizedGainLoss).toLocaleString()}`)
    lines.push('')

    if (ps.ordinaryIncomeFromPortfolio > 0) {
      lines.push('ORDINARY INCOME FROM PORTFOLIO:')
      if (ps.stakingRewards > 0) lines.push(`  Staking Rewards: $${Math.round(ps.stakingRewards).toLocaleString()} (Schedule 1 / Schedule C)`)
      if (ps.airdropIncome > 0) lines.push(`  Airdrop Income: $${Math.round(ps.airdropIncome).toLocaleString()} (FMV at receipt — ordinary income)`)
      if (ps.miningIncome > 0) lines.push(`  Mining Income: $${Math.round(ps.miningIncome).toLocaleString()} (Schedule C if business activity)`)
      lines.push(`  Total: $${Math.round(ps.ordinaryIncomeFromPortfolio).toLocaleString()}`)
      lines.push('')
    }

    if (f8949.lines.length > 0) {
      lines.push('FORM 8949 / SCHEDULE D — CAPITAL GAINS & LOSSES:')
      lines.push('')
      lines.push('Short-Term (held < 1 year):')
      const stLines = f8949.lines.filter(l => l.holdingPeriod === 'short')
      if (stLines.length > 0) {
        for (const l of stLines) {
          lines.push(`  ${l.description}`)
          lines.push(`    Acquired: ${l.dateAcquired} | Sold: ${l.dateSold} | Proceeds: $${Math.round(l.proceeds).toLocaleString()} | Basis: $${Math.round(l.costBasis).toLocaleString()} | ${l.gainLoss >= 0 ? 'Gain' : 'Loss'}: ${l.gainLoss >= 0 ? '+' : ''}$${Math.round(l.gainLoss).toLocaleString()}`)
        }
        lines.push(`  SUBTOTAL: Proceeds $${Math.round(f8949.shortTermTotal.proceeds).toLocaleString()} | Basis $${Math.round(f8949.shortTermTotal.basis).toLocaleString()} | Net ${f8949.shortTermTotal.gainLoss >= 0 ? '+' : ''}$${Math.round(f8949.shortTermTotal.gainLoss).toLocaleString()}`)
      } else {
        lines.push('  (none)')
      }
      lines.push('')
      lines.push('Long-Term (held >= 1 year):')
      const ltLines = f8949.lines.filter(l => l.holdingPeriod === 'long')
      if (ltLines.length > 0) {
        for (const l of ltLines) {
          lines.push(`  ${l.description}`)
          lines.push(`    Acquired: ${l.dateAcquired} | Sold: ${l.dateSold} | Proceeds: $${Math.round(l.proceeds).toLocaleString()} | Basis: $${Math.round(l.costBasis).toLocaleString()} | ${l.gainLoss >= 0 ? 'Gain' : 'Loss'}: ${l.gainLoss >= 0 ? '+' : ''}$${Math.round(l.gainLoss).toLocaleString()}`)
        }
        lines.push(`  SUBTOTAL: Proceeds $${Math.round(f8949.longTermTotal.proceeds).toLocaleString()} | Basis $${Math.round(f8949.longTermTotal.basis).toLocaleString()} | Net ${f8949.longTermTotal.gainLoss >= 0 ? '+' : ''}$${Math.round(f8949.longTermTotal.gainLoss).toLocaleString()}`)
      } else {
        lines.push('  (none)')
      }
      lines.push('')
      lines.push(`NET CAPITAL GAIN/LOSS: ${f8949.netCapitalGainLoss >= 0 ? '+' : ''}$${Math.round(f8949.netCapitalGainLoss).toLocaleString()}`)
      if (f8949.netCapitalGainLoss < 0) {
        lines.push(`  Capital loss deduction (max $3,000/yr): $${Math.min(3000, Math.abs(f8949.netCapitalGainLoss)).toLocaleString()}`)
        if (Math.abs(f8949.netCapitalGainLoss) > 3000) {
          lines.push(`  Carryforward to next year: $${(Math.abs(f8949.netCapitalGainLoss) - 3000).toLocaleString()}`)
        }
      }
      lines.push('')
    }

    const pendingEvents = portfolio.taxEvents.filter(e => !e.realized)
    if (pendingEvents.length > 0) {
      lines.push('PENDING TAXABLE EVENTS (not yet realized):')
      for (const evt of pendingEvents) {
        lines.push(`  - ${evt.description}: ~$${Math.round(evt.estimatedAmount).toLocaleString()} (${evt.taxTreatment.replace(/_/g, ' ')})${evt.expectedDate ? ' — expected ' + evt.expectedDate : ''}`)
      }
      lines.push('')
    }

    lines.push('DOCUMENTATION NEEDED:')
    lines.push('  □ 1099-B from all exchanges/brokerages')
    lines.push('  □ Transaction history export from crypto exchanges')
    lines.push('  □ Wallet transaction records (on-chain)')
    if (ps.stakingRewards > 0) lines.push('  □ Staking reward records with FMV at time of receipt')
    if (ps.airdropIncome > 0) lines.push('  □ Airdrop documentation with FMV screenshots')
    if (ps.miningIncome > 0) lines.push('  □ Mining income records (electricity costs for deduction)')
    lines.push('  □ Cost basis records for each position')

    sections.push({
      title: 'INVESTMENT & PORTFOLIO (Schedule D / Form 8949)',
      content: lines.join('\n'),
    })
  }

  sections.push({
    title: 'KEY TAX DEADLINES',
    content: [
      `January 15:   Q4 estimated tax payment due`,
      `March 15:     S-Corp/Partnership returns due (Form 1120-S, 1065)`,
      `April 15:     Individual return due (Form 1040) / Q1 estimated payment`,
      `              IRA/Roth IRA contribution deadline for prior year`,
      `June 15:      Q2 estimated tax payment due`,
      `September 15: Q3 estimated tax payment / Extended S-Corp deadline`,
      `October 15:   Extended individual return deadline`,
      `December 31:  Solo 401(k) employee deferral deadline`,
      `              Tax-loss harvesting deadline`,
      `              Entity election deadline for next tax year`,
    ].join('\n'),
  })

  // ─── Compile ───────────────────────────────────────────────────────

  const separator = '═'.repeat(80)
  const rawText = [
    separator,
    `  FORTUNA TAX PREPARATION PACKAGE — ${year}`,
    `  Prepared for: ${profile.name || 'Client'}`,
    `  Generated: ${new Date().toISOString().split('T')[0]}`,
    separator,
    '',
    ...sections.map(s => [
      `┌${'─'.repeat(78)}┐`,
      `│  ${s.title.padEnd(76)}│`,
      `└${'─'.repeat(78)}┘`,
      '',
      s.content,
      '',
    ].join('\n')),
    separator,
    '  DISCLAIMER: This report is generated by Fortuna Engine for informational',
    '  purposes only. It does not constitute tax advice. Consult a qualified',
    '  tax professional before making tax-related decisions.',
    separator,
  ].join('\n')

  return {
    generatedDate: new Date().toISOString(),
    taxYear: year,
    clientName: profile.name || 'Client',
    filingStatus: profile.filingStatus || 'single',
    state: profile.state || 'N/A',
    sections,
    rawText,
  }
}
